spring.application.name=spring-la-mia-pizzeria-crud


##connessione al db
spring.datasource.url=jdbc:mysql://localhost:3306/pizzeria
spring.datasource.username=root
spring.datasource.password=root

#linguaggio del db
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect

#tipo di comportamento con il db: create, create-drop, validate, update, none
#create: inserisce e cancella subito, create drop crea e mantiene finche la sessione è attiva, update cambia o aggiunge, validate??
spring.jpa.hibernate.ddl-auto=update 

#impostazioni per il testing
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql=true